# Demostração do Numpy
### Disciplina de Ciência de Dados

#### Importação de Bibliotecas

In [14]:
import numpy as np

### Gerar dados aliatorios

#### Gerar um NDArray de 2x3 (duas listas com 3 elementos)

In [19]:
dados = np.random.rand(2, 3)
dados

array([[0.0173815 , 0.7778883 , 0.12078748],
       [0.05640311, 0.68001821, 0.56788525]])

#### Tipo de Array

In [24]:
dados.dtype

dtype('float64')

#### Tamanho e quantidade de dimensões

In [29]:
dados.shape

(2, 3)

In [31]:
dados.ndim

2

 ### Criar ndarry usando a função arry
 #### Ao criar o arry, a função tenta utilizar o melhor tipo de dado

In [34]:
lista = [1, 2, 5, 7.8, 1.25]

In [40]:
dados2 = np.array(lista)
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [44]:
lista2 = [[1, 2, 3, 4], [4, 3, 2, 1]]

In [50]:
dados3 = np.array(lista2)
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### Outras maneiras de criar arrays

In [55]:
# Criar array de 10 posicoes com todos valores zeros
dadoszero = np.zeros(10)
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
dadoszero2 = np.zeros((2, 3))
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
dadosum = np.ones(5)
dadosum

array([1., 1., 1., 1., 1.])

In [65]:
dadosum2 = np.ones((2, 3))
dadosum2

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Criando valores sequencias

In [70]:
dadoseq = np.arange(10) 
dadoseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
dadoseq2 = np.arange(0, 20, 2)
dadoseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
dadoseq2.dtype

dtype('int32')

In [78]:
dadoseqf = dadoseq.astype(np.float64)
dadoseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
dadoseqf.dtype

dtype('float64')

## Aritmética com Arrays

In [85]:
dados4 = np.array([[1, 2, 3], [4, 5, 6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])