# Demostração do Numpy
### Disciplina de Ciência de Dados

#### Importação de Bibliotecas

In [14]:
import numpy as np

### Gerar dados aliatorios

#### Gerar um NDArray de 2x3 (duas listas com 3 elementos)

In [19]:
dados = np.random.rand(2, 3)
dados

array([[0.0173815 , 0.7778883 , 0.12078748],
       [0.05640311, 0.68001821, 0.56788525]])

#### Tipo de Array

In [24]:
dados.dtype

dtype('float64')

#### Tamanho e quantidade de dimensões

In [29]:
dados.shape

(2, 3)

In [31]:
dados.ndim

2

 ### Criar ndarry usando a função arry
 #### Ao criar o arry, a função tenta utilizar o melhor tipo de dado

In [34]:
lista = [1, 2, 5, 7.8, 1.25]

In [40]:
dados2 = np.array(lista)
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [44]:
lista2 = [[1, 2, 3, 4], [4, 3, 2, 1]]

In [50]:
dados3 = np.array(lista2)
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### Outras maneiras de criar arrays

In [55]:
# Criar array de 10 posicoes com todos valores zeros
dadoszero = np.zeros(10)
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
dadoszero2 = np.zeros((2, 3))
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
dadosum = np.ones(5)
dadosum

array([1., 1., 1., 1., 1.])

In [65]:
dadosum2 = np.ones((2, 3))
dadosum2

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Criando valores sequencias

In [70]:
dadoseq = np.arange(10) 
dadoseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
dadoseq2 = np.arange(0, 20, 2)
dadoseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
dadoseq2.dtype

dtype('int32')

In [78]:
dadoseqf = dadoseq.astype(np.float64)
dadoseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
dadoseqf.dtype

dtype('float64')

## Aritmética com Arrays

In [85]:
dados4 = np.array([[1, 2, 3], [4, 5, 6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
dados4 * dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [89]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [91]:
1 / dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [93]:
2 * dados4

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [95]:
dados5 = dados4 + dados4
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [97]:
dados4 > dados5

array([[False, False, False],
       [False, False, False]])

## Indexação

In [100]:
dadoseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
dadoseq[5]

5

In [104]:
dadoseq[(1+2)]

3

#### Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá brodcast - é como se fosse uma view de base de dados.
#### Com conjuntos imensos de dados, isso é uma grande vantagem em relação a performance

In [110]:
dadoseq[3:6]

array([3, 4, 5])

In [114]:
dadoseq[3:5] = 20
dadoseq

array([ 0,  1,  2, 20, 20,  5,  6,  7,  8,  9])

In [134]:
dadosfatia = dadoseq[2:4]
dadosfatia

array([ 33, 333])

In [136]:
dadosfatia[1] = 2000
dadosfatia

array([  33, 2000])

In [138]:
dadoseq

array([   0,    1,   33, 2000,   20,    5,    6,    7,    8,    9])

In [140]:
dadosfatia[:] = 333
dadosfatia

array([333, 333])

In [142]:
dadoseq

array([  0,   1, 333, 333,  20,   5,   6,   7,   8,   9])

In [144]:
dadoseq[2] = 33
dadoseq

array([  0,   1,  33, 333,  20,   5,   6,   7,   8,   9])

In [146]:
dadosfatia

array([ 33, 333])

### Copiar dados

In [154]:
dadosfatia2 = dadoseq[2:4].copy()
dadosfatia2

array([ 33, 333])

In [156]:
dadosfatia2[:] = 111
dadosfatia2

array([111, 111])

In [158]:
dadoseq

array([  0,   1,  33, 333,  20,   5,   6,   7,   8,   9])

### Array com mais de uma dimensão

In [164]:
dados6 = np.array([[1, 2, 3], [4, 5, 6], [7,  8, 9]])
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
dados6[1, 2]

6

### Mascaras 

In [170]:
dadoseq

array([  0,   1,  33, 333,  20,   5,   6,   7,   8,   9])

In [174]:
mascara = dadoseq < 100
mascara

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [178]:
dadoseq[dadoseq < 20] = 8888
dadoseq

array([8888, 8888,   33,  333,   20, 8888, 8888, 8888, 8888, 8888])

### Transposição

In [183]:
dados7 = np.arange(15).reshape((3, 5))
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [185]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Multiplicação de matrizes com Dots

In [188]:
np.dot(dados7.T, dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

### Vejam que há muitas outras funções que podem ser exploradas como: 
### sin, cos, power, mod, sqrt entre outros

## Pandas

### Disciplina de Ciência de Dados
### Aula 6

#### Importação da Biblioteca Pandas

In [8]:
import pandas as pd
import numpy as np

#### Series (observar o indece do lado esquerdo)

In [12]:
s1 = pd.Series([1, 2, -5, 0])
s1

0    1
1    2
2   -5
3    0
dtype: int64

In [14]:
s1.values

array([ 1,  2, -5,  0], dtype=int64)

In [16]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
s2 = pd.Series([1, 2, -5, 0], index = ['a', 'b', 'c', 'd'])
s2

a    1
b    2
c   -5
d    0
dtype: int64

In [20]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

#### Atribuição

In [23]:
s2['a'] = 1000
s2

a    1000
b       2
c      -5
d       0
dtype: int64

#### Comparação

In [28]:
s2[s2 > 0]

a    1000
b       2
dtype: int64

#### Algebra

In [30]:
s2 * 2

a    2000
b       4
c     -10
d       0
dtype: int64

In [32]:
s1.isnull()

0    False
1    False
2    False
3    False
dtype: bool

### Dataframe

In [35]:
# Dicionario
dados = {
    'estado': ['SP', 'MG', 'PR', 'SP', 'MG', 'PR'], 
    'ano': [2019, 2019, 2019, 2020, 2020, 2020],
    'pop': [45.9, 21.2, 16.9, 46.6, 21.4, 17.3]
}

In [37]:
# Dataframe
df1 = pd.DataFrame(dados)
df1

estado   ano   pop
0     SP  2019  45.9
1     MG  2019  21.2
2     PR  2019  16.9
3     SP  2020  46.6
4     MG  2020  21.4
5     PR  2020  17.3

#### Visualizar partes do dataframe

In [46]:
# Prmeiros linhas
df1.head(2)

estado   ano   pop
0     SP  2019  45.9
1     MG  2019  21.2

In [50]:
# Ultimas linghas
df1.tail(2)

estado   ano   pop
4     MG  2020  21.4
5     PR  2020  17.3

In [52]:
# Linhas aliatorias
df1.sample(3)

estado   ano   pop
2     PR  2019  16.9
5     PR  2020  17.3
3     SP  2020  46.6

### Criar novo Dataframe definindo a posição das colunas 

In [55]:
df2 = pd.DataFrame(dados, columns = ['ano', 'estado', 'pop'])
df2

ano estado   pop
0  2019     SP  45.9
1  2019     MG  21.2
2  2019     PR  16.9
3  2020     SP  46.6
4  2020     MG  21.4
5  2020     PR  17.3

#### Observar DF

In [59]:
df2['estado']

0    SP
1    MG
2    PR
3    SP
4    MG
5    PR
Name: estado, dtype: object

In [63]:
df2.ano

0    2019
1    2019
2    2019
3    2020
4    2020
5    2020
Name: ano, dtype: int64

In [61]:
df2[['estado', 'ano']]

estado   ano
0     SP  2019
1     MG  2019
2     PR  2019
3     SP  2020
4     MG  2020
5     PR  2020

In [67]:
df2.dtypes

ano         int64
estado     object
pop       float64
dtype: object

#### Atribuir valores

In [72]:
df2['estimativa'] = 50
df2

ano estado   pop  estimativa
0  2019     SP  45.9          50
1  2019     MG  21.2          50
2  2019     PR  16.9          50
3  2020     SP  46.6          50
4  2020     MG  21.4          50
5  2020     PR  17.3          50

In [74]:
df2['estimativa'] = np.arange(6)
df2

ano estado   pop  estimativa
0  2019     SP  45.9           0
1  2019     MG  21.2           1
2  2019     PR  16.9           2
3  2020     SP  46.6           3
4  2020     MG  21.4           4
5  2020     PR  17.3           5

In [76]:
df3 = df2
df3

ano estado   pop  estimativa
0  2019     SP  45.9           0
1  2019     MG  21.2           1
2  2019     PR  16.9           2
3  2020     SP  46.6           3
4  2020     MG  21.4           4
5  2020     PR  17.3           5

In [78]:
df3 = df2['ano']
df3

0    2019
1    2019
2    2019
3    2020
4    2020
5    2020
Name: ano, dtype: int64